function write_cost_table(cost_table, tex_path)
% DF.REPORT.WRITE_COST_TABLE  Write computational cost table for R1.1.b.
%
%   df.report.write_cost_table(cost_table, tex_path)
%
%   Generates a LaTeX table showing computational costs by (s, T) with
%   columns for grid size, learning time, solve time, total time, and
%   identified set statistics. Responds to R1.1.b: "provide a table
%   showing the computational costs with different specifications."
%
%   Inputs:
%     cost_table — struct array with fields:
%       .s, .NGrid, .maxiters, .t_learn, .t_obj, .t_solve, .t_total,
%       .n_identified, .pct_identified
%     tex_path   — output .tex file path
%
%   The table uses booktabs and dcolumn (project convention).

n = numel(cost_table);
if n == 0
    warning('Empty cost table — nothing to write.');
    return;
end

% Also write a .mat for downstream use
[fdir, fname] = fileparts(tex_path);
save(fullfile(fdir, [fname '.mat']), 'cost_table');

% Build LaTeX
fid = fopen(tex_path, 'w');

fprintf(fid, '%% Auto-generated by df.report.write_cost_table\n');
fprintf(fid, '\\begin{table}[htbp]\n');
fprintf(fid, '\\centering\n');
fprintf(fid, '\\caption{Computational costs: nonparametric identification}\n');
fprintf(fid, '\\label{tab:nonparam_cost}\n');
fprintf(fid, '\\arraystretch{1.1}\n');
fprintf(fid, '\\begin{tabular}{rr rD{.}{.}{1}D{.}{.}{1}D{.}{.}{1}D{.}{.}{1} rD{.}{.}{1}}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, '$s$ & Grid & $T$ (k) & \\multicolumn{1}{c}{Learn (s)} & \\multicolumn{1}{c}{Obj (s)} & \\multicolumn{1}{c}{Solve (s)} & \\multicolumn{1}{c}{Total (s)} & $|\\mathcal{I}|$ & \\multicolumn{1}{c}{\\%%} \\\\\n');
fprintf(fid, '\\midrule\n');

prev_s = -1;
for i = 1:n
    r = cost_table(i);
    if r.s ~= prev_s && prev_s > 0
        fprintf(fid, '\\addlinespace\n');
    end
    prev_s = r.s;

    fprintf(fid, '%d & %d & %d & %.1f & %.1f & %.1f & %.1f & %d & %.1f \\\\\n', ...
        r.s, r.NGrid, r.maxiters/1000, ...
        r.t_learn, r.t_obj, r.t_solve, r.t_total, ...
        r.n_identified, r.pct_identified);
end

fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fprintf(fid, '\\begin{tablenotes}\\small\n');
fprintf(fid, '\\item Grid = number of candidate distributions. $|\\mathcal{I}|$ = identified candidates ($V \\leq 10^{-12}$).\n');
fprintf(fid, '\\item Learn: regret-matching simulation. Obj: objective vector construction. Solve: CVX+SeDuMi SOCP batch.\n');
fprintf(fid, '\\end{tablenotes}\n');
fprintf(fid, '\\end{table}\n');

fclose(fid);
fprintf('[write_cost_table] Wrote %s (%d rows)\n', tex_path, n);

end
