function [distY_time, distY_time_obs, final_regret_pooled, final_regret_type, ...
          Pl1_EmpRegr, Pl2_EmpRegr] = ...
    learn_mod_pooled(cfg, N, M, M_obs, numdst_t, numdst_t_obs, Nobs_Pl1, Nobs_Pl2)
% learn_mod_pooled  Pooled-regret learning simulation (thin wrapper).
%
%   Unconditional / strategic-normal-form variant of learn_mod. Delegates to
%   df.sim.learn_pooled. See that function for details.
%
%   [distY_time, distY_time_obs, final_regret_pooled, final_regret_type, ...
%       Pl1_EmpRegr, Pl2_EmpRegr] = ...
%       learn_mod_pooled(cfg, N, M, M_obs, numdst_t, numdst_t_obs, Nobs_Pl1, Nobs_Pl2)

[distY_time, distY_time_obs, final_regret_pooled, final_regret_type, ...
 Pl1_EmpRegr, Pl2_EmpRegr] = ...
    df.sim.learn_pooled(cfg, N, M, M_obs, numdst_t, numdst_t_obs, Nobs_Pl1, Nobs_Pl2);

end
